# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('voter_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
