# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0002_auto_20170308_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot_title', models.CharField(max_length=500)),
                ('ballot_short_desc', models.CharField(max_length=500)),
                ('ballot_instruction', models.CharField(max_length=500)),
                ('type', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vote_deadline', models.DateTimeField(verbose_name='vote_deadline')),
            ],
        ),
        migrations.CreateModel(
            name='LogHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.CreateModel(
            name='CustomOption',
            fields=[
                ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='voteapp.Option')),
                ('input_text', models.CharField(max_length=200)),
            ],
            bases=('voteapp.option',),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='option',
            name='ballot_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.Ballot'),
        ),
        migrations.AddField(
            model_name='loghistory',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.Option'),
        ),
        migrations.AddField(
            model_name='loghistory',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.Voter'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.Election'),
        ),
        migrations.AddField(
            model_name='voter',
            name='election',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='voteapp.Election'),
            preserve_default=False,
        ),
    ]
