# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0003_auto_20170308_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customoption',
            old_name='input_text',
            new_name='custom_text',
        ),
        migrations.AddField(
            model_name='ballot',
            name='allow_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ballot',
            name='max_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ballot',
            name='required_num',
            field=models.IntegerField(default=1),
        ),
    ]
