# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0004_auto_20170308_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='ballot_instruction',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='ballot_short_desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='required_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='type',
            field=models.CharField(default='radio', max_length=200),
        ),
    ]
