# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0007_auto_20170308_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ballot',
            old_name='ballot_short_desc',
            new_name='ballot_details',
        ),
        migrations.RenameField(
            model_name='ballot',
            old_name='ballot_instruction',
            new_name='how_to_vote',
        ),
        migrations.AddField(
            model_name='ballot',
            name='ballot_issue',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
