# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0008_auto_20170308_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ballot',
            old_name='ballot_issue',
            new_name='ballot_question',
        ),
    ]
