# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0009_auto_20170308_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='display_order',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='option',
            name='display_order',
            field=models.IntegerField(default=10),
        ),
    ]
