# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0010_auto_20170309_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='ballot_details',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='ballot_question',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='ballot_title',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='how_to_vote',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='type',
            field=models.TextField(default='radio', max_length=200),
        ),
        migrations.AlterField(
            model_name='customoption',
            name='custom_text',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_text',
            field=models.TextField(max_length=200),
        ),
    ]
