# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0011_auto_20170309_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=20)),
                ('href', models.CharField(max_length=30)),
                ('display_order', models.IntegerField(default=10)),
            ],
        ),
    ]
