# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 17:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voteapp', '0013_delete_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='loghistory',
            name='election',
        ),
        migrations.RemoveField(
            model_name='loghistory',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='option',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='voter_id',
        ),
        migrations.AddField(
            model_name='voter',
            name='voter_user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LogHistory',
        ),
        migrations.AddField(
            model_name='votes',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.Option'),
        ),
        migrations.AddField(
            model_name='votes',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.Voter'),
        ),
    ]
