# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0014_auto_20170311_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.Option')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.Voter')),
            ],
        ),
    ]
