# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0015_loghistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='voter_user',
            new_name='voter_usr',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='election',
        ),
        migrations.AddField(
            model_name='election',
            name='voters',
            field=models.ManyToManyField(related_name='voter_user', to='voteapp.Voter'),
        ),
    ]
