# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0016_auto_20170311_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='voter_usr',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='election',
            name='voters',
            field=models.ManyToManyField(to='voteapp.Voter'),
        ),
    ]
