# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 21:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voteapp', '0018_auto_20170311_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteInOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_text', models.TextField(max_length=200)),
                ('display_order', models.IntegerField(default=100)),
                ('ballot_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.Ballot')),
                ('voters', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='customoption',
            name='option_ptr',
        ),
        migrations.DeleteModel(
            name='CustomOption',
        ),
    ]
