# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0019_auto_20170311_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='custom_option',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='voteapp.WriteInOption'),
            preserve_default=False,
        ),
    ]
