# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0020_votes_custom_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writeinoption',
            old_name='custom_text',
            new_name='option_text',
        ),
    ]
