# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0021_auto_20170311_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='custom_option',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='voteapp.WriteInOption'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='option',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='voteapp.Option'),
        ),
    ]
