# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0022_auto_20170311_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='value',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
