# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0023_votes_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='ballot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='voteapp.Ballot'),
            preserve_default=False,
        ),
    ]
