# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0025_auto_20170312_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='custom_option',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='voteapp.WriteInOption'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='option',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='voteapp.Option'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
