# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0026_auto_20170312_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loghistory',
            name='election',
        ),
        migrations.AddField(
            model_name='loghistory',
            name='action',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
